connections {
	gw-gw {
		local_addrs  = 192.168.31.13
		remote_addrs = 192.168.31.11

		local {
			auth = psk
			id = keyid:123
		}
                                                                                                                                              
		remote {
			auth = psk
			id = magnit.ru
		}

		children {
			net-net {
				local_ts  = 48.0.0.0/8
				remote_ts = 16.0.0.0/8
			}
		}
		version = 2
	}
}

secrets {
	ike-1 {
		secret = 0sv+NkxY9LLZvwj4qCC2o/gGrWDF2d21jL
	}
}

