unix
{
        interactive 
        nodaemon
        exec /etc/vpp/startup-config
}

plugins
{
        plugin dpdk_plugin.so { enable }
        plugin linux_cp_plugin.so { enable }
        plugin linux_nl_plugin.so {enable }
        plugin ikev2_plugin.so { enable }
}

cpu
{
        main-core 0
        corelist-workers 1,2
}

linux-cp
{
        lcp-sync
}

dpdk
{
        dev 0000:08:00.1
        {
                num-rx-queues 2
                num-tx-queues 2
        }

        dev 0000:09:00.0
        {
                num-rx-queues 2
                num-tx-queues 2
        }
}
