unix {
	nodaemon
	log /var/log/vpp.log
	full-coredump
	cli-listen /run/vpp/cli.sock
	gid vpp
	pidfile /run/vpp.pid
	interactive
}

plugins {
	plugin dpdk_plugin.so  { disable }
}

cpu {
	main-core 0
	corelist-workers 1-24
}

nat44-ed {
	in2out-ip-fib-index
}

statseg {
	size 500m
}

memory {
	main-heap-size 50G
}

buffers {
	buffers-per-numa 128000
}

#dpdk {
#  dev 0000:3b:00.0 { num-rx-queues 1 num-tx-queues 1  name ens1f0 }
#}
