connections {
	gw-gw {
		local_addrs  = 192.168.31.11
		remote_addrs = 0.0.0.0

		local {
			auth = psk
			id = magnit.ru
		}
		remote {
			auth = psk
			id = keyid:123
		}
		children {
			net-net {
				local_ts  = 16.0.0.0/8
				remote_ts = 48.0.0.0/8

				rekey_time = 5400
				rekey_bytes = 500000000
				rekey_packets = 1000000
			}
		}
		version = 2
	}
}

secrets {
	ike-1 {
		secret = 0sv+NkxY9LLZvwj4qCC2o/gGrWDF2d21jL
	}
}
